---
name: Push/Pull actions

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main

  pull_request:

jobs:
  validate:
    runs-on: "ubuntu-latest"
    name: Validate
    steps:
      - uses: "actions/checkout@v3"

      - name: HACS validation
        uses: "hacs/action@main"
        with:
          CATEGORY: "integration"

      - name: Hassfest validation
        uses: "home-assistant/actions/hassfest@master"

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.x
      - uses: pre-commit/action@v3.0.0
